language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "haopoboy-github"
    token:
      secure: "${SONAR_TOKEN}"
      
cache:
  directories:
  - .autoconf
  - $HOME/.m2
      
script:
  - mvn clean package sonar:sonar  