language: java
jdk:
  - openjdk8
  
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME=docmd
    - GCLOUD_PROJECT_ID=lofty-reserve-109616

addons:
  sonarcloud:
    organization: "haopoboy-github"
    token:
      secure: "${SONAR_TOKEN}"
      
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/google-cloud-sdk
  - .$HOME/sonar/cache
  
services:
  - docker
      
script:
  - mvn clean package sonar:sonar
  
deploy:
  - provider: script
    script: chmod +x gcloud/deploy.sh && gcloud/deploy.sh
    skip_cleanup: true
    on:
      branch: master